# Create these secrets before deploying Coder
# kubectl apply -f required-secrets.yaml
# Note: TLS certificate secret not needed when using ALB with ACM

---
# Database connection secret
apiVersion: v1
kind: Secret
metadata:
  name: coder-db-secret
  namespace: coder  # Replace with your namespace
type: Opaque
data:
  # Base64 encoded PostgreSQL connection URL
  # Format: postgres://username:password@host:port/database?sslmode=require
  connection-url: <BASE64_ENCODED_PG_URL>

---
# ForgeRock OIDC secret
apiVersion: v1
kind: Secret
metadata:
  name: coder-oidc-secret
  namespace: coder
type: Opaque
data:
  # Base64 encoded ForgeRock OIDC client credentials
  client-id: <BASE64_ENCODED_CLIENT_ID>
  client-secret: <BASE64_ENCODED_CLIENT_SECRET>

---
# GitHub external auth secret
apiVersion: v1
kind: Secret
metadata:
  name: coder-github-secret
  namespace: coder
type: Opaque
data:
  # Base64 encoded GitHub OAuth app credentials
  client-id: <BASE64_ENCODED_GITHUB_CLIENT_ID>
  client-secret: <BASE64_ENCODED_GITHUB_CLIENT_SECRET>
